SKIPUNZIP=0
set_perm_recursive $MODPATH 0 0 0755 0644
set_perm $MODPATH/btbcm.ko
set_perm $MODPATH/ieee802154.ko
set_perm $MODPATH/nhc_routing.ko
set_perm $MODPATH/kunit.ko
set_perm $MODPATH/diag.ko
set_perm $MODPATH/pptp.ko
set_perm $MODPATH/nhc_mobility.ko
set_perm $MODPATH/soc-utils-test.ko
set_perm $MODPATH/usbserial.ko
set_perm $MODPATH/virtio_balloon.ko
set_perm $MODPATH/vmw_vsock_virtio_transport.ko
set_perm $MODPATH/macsec.ko
set_perm $MODPATH/virtio_blk.ko
set_perm $MODPATH/r8152.ko
set_perm $MODPATH/time_test.ko
set_perm $MODPATH/nhc_dest.ko
set_perm $MODPATH/open-dice.ko
set_perm $MODPATH/bluetooth.ko
set_perm $MODPATH/6lowpan.ko
set_perm $MODPATH/ppp_mppe.ko
set_perm $MODPATH/virtio_pci.ko
set_perm $MODPATH/l2tp_core.ko
set_perm $MODPATH/rfkill.ko
set_perm $MODPATH/slhc.ko
set_perm $MODPATH/clk-gate_test.ko
set_perm $MODPATH/btqca.ko
set_perm $MODPATH/ieee802154_6lowpan.ko
set_perm $MODPATH/ieee802154_socket.ko
set_perm $MODPATH/vcpu_stall_detector.ko
set_perm $MODPATH/nhc_hop.ko
set_perm $MODPATH/ppp_generic.ko
set_perm $MODPATH/slcan.ko
set_perm $MODPATH/iio-test-format.ko
set_perm $MODPATH/libarc4.ko
set_perm $MODPATH/usbmon.ko
set_perm $MODPATH/wwan.ko
set_perm $MODPATH/9pnet_fd.ko
set_perm $MODPATH/asix.ko
set_perm $MODPATH/input_test.ko
set_perm $MODPATH/virtio_console.ko
set_perm $MODPATH/hid-uclogic-test.ko
set_perm $MODPATH/cdc-acm.ko
set_perm $MODPATH/dev_addr_lists_test.ko
set_perm $MODPATH/rfcomm.ko
set_perm $MODPATH/cdc_eem.ko
set_perm $MODPATH/clk_test.ko
set_perm $MODPATH/fat_test.ko
set_perm $MODPATH/nhc_udp.ko
set_perm $MODPATH/zram.ko
set_perm $MODPATH/lib_test.ko
set_perm $MODPATH/9pnet.ko
set_perm $MODPATH/can-bcm.ko
set_perm $MODPATH/tipc.ko
set_perm $MODPATH/zsmalloc.ko
set_perm $MODPATH/ax88179_178a.ko
set_perm $MODPATH/cdc_ether.ko
set_perm $MODPATH/mii.ko
set_perm $MODPATH/usbnet.ko
set_perm $MODPATH/aqc111.ko
set_perm $MODPATH/8021q.ko
set_perm $MODPATH/regmap-raw-ram.ko
set_perm $MODPATH/mac802154.ko
set_perm $MODPATH/nfc.ko
set_perm $MODPATH/can.ko
set_perm $MODPATH/can-gw.ko
set_perm $MODPATH/ppp_deflate.ko
set_perm $MODPATH/ptp_kvm.ko
set_perm $MODPATH/pps_core.ko
set_perm $MODPATH/kunit-test.ko
set_perm $MODPATH/ext4-inode-test.ko
set_perm $MODPATH/kheaders.ko
set_perm $MODPATH/can-raw.ko
set_perm $MODPATH/gzvm.ko
set_perm $MODPATH/vcan.ko
set_perm $MODPATH/virtio_pci_modern_dev.ko
set_perm $MODPATH/pppox.ko
set_perm $MODPATH/nhc_fragment.ko
set_perm $MODPATH/l2tp_ppp.ko
set_perm $MODPATH/cctrng.ko
set_perm $MODPATH/btsdio.ko
set_perm $MODPATH/regmap-ram.ko
set_perm $MODPATH/rtl8150.ko
set_perm $MODPATH/nhc_ipv6.ko
set_perm $MODPATH/hci_uart.ko
set_perm $MODPATH/ptp.ko
set_perm $MODPATH/bsd_comp.ko
set_perm $MODPATH/can-dev.ko
set_perm $MODPATH/hidp.ko
set_perm $MODPATH/regmap-kunit.ko
set_perm $MODPATH/cdc_ncm.ko
set_perm $MODPATH/ftdi_sio.ko
set_perm $MODPATH/kunit-example-test.ko
set_perm $MODPATH/r8153_ecm.ko
set_perm $MODPATH/soc-topology-test.ko


