#!/system/bin/sh
MODDIR=${0%/modules}
insmod "$MODDIR"/btbcm.ko
insmod "$MODDIR"/ieee802154.ko
insmod "$MODDIR"/nhc_routing.ko
insmod "$MODDIR"/kunit.ko
insmod "$MODDIR"/diag.ko
insmod "$MODDIR"/pptp.ko
insmod "$MODDIR"/nhc_mobility.ko
insmod "$MODDIR"/soc-utils-test.ko
insmod "$MODDIR"/usbserial.ko
insmod "$MODDIR"/virtio_balloon.ko
insmod "$MODDIR"/vmw_vsock_virtio_transport.ko
insmod "$MODDIR"/macsec.ko
insmod "$MODDIR"/virtio_blk.ko
insmod "$MODDIR"/r8152.ko
insmod "$MODDIR"/time_test.ko
insmod "$MODDIR"/nhc_dest.ko
insmod "$MODDIR"/open-dice.ko
insmod "$MODDIR"/bluetooth.ko
insmod "$MODDIR"/6lowpan.ko
insmod "$MODDIR"/ppp_mppe.ko
insmod "$MODDIR"/virtio_pci.ko
insmod "$MODDIR"/l2tp_core.ko
insmod "$MODDIR"/rfkill.ko
insmod "$MODDIR"/slhc.ko
insmod "$MODDIR"/clk-gate_test.ko
insmod "$MODDIR"/btqca.ko
insmod "$MODDIR"/ieee802154_6lowpan.ko
insmod "$MODDIR"/ieee802154_socket.ko
insmod "$MODDIR"/vcpu_stall_detector.ko
insmod "$MODDIR"/nhc_hop.ko
insmod "$MODDIR"/ppp_generic.ko
insmod "$MODDIR"/slcan.ko
insmod "$MODDIR"/iio-test-format.ko
insmod "$MODDIR"/libarc4.ko
insmod "$MODDIR"/usbmon.ko
insmod "$MODDIR"/wwan.ko
insmod "$MODDIR"/9pnet_fd.ko
insmod "$MODDIR"/asix.ko
insmod "$MODDIR"/input_test.ko
insmod "$MODDIR"/virtio_console.ko
insmod "$MODDIR"/hid-uclogic-test.ko
insmod "$MODDIR"/cdc-acm.ko
insmod "$MODDIR"/dev_addr_lists_test.ko
insmod "$MODDIR"/rfcomm.ko
insmod "$MODDIR"/cdc_eem.ko
insmod "$MODDIR"/clk_test.ko
insmod "$MODDIR"/fat_test.ko
insmod "$MODDIR"/nhc_udp.ko
insmod "$MODDIR"/zram.ko
insmod "$MODDIR"/lib_test.ko
insmod "$MODDIR"/9pnet.ko
insmod "$MODDIR"/can-bcm.ko
insmod "$MODDIR"/tipc.ko
insmod "$MODDIR"/zsmalloc.ko
insmod "$MODDIR"/ax88179_178a.ko
insmod "$MODDIR"/cdc_ether.ko
insmod "$MODDIR"/mii.ko
insmod "$MODDIR"/usbnet.ko
insmod "$MODDIR"/aqc111.ko
insmod "$MODDIR"/8021q.ko
insmod "$MODDIR"/regmap-raw-ram.ko
insmod "$MODDIR"/mac802154.ko
insmod "$MODDIR"/nfc.ko
insmod "$MODDIR"/can.ko
insmod "$MODDIR"/can-gw.ko
insmod "$MODDIR"/ppp_deflate.ko
insmod "$MODDIR"/ptp_kvm.ko
insmod "$MODDIR"/pps_core.ko
insmod "$MODDIR"/kunit-test.ko
insmod "$MODDIR"/ext4-inode-test.ko
insmod "$MODDIR"/kheaders.ko
insmod "$MODDIR"/can-raw.ko
insmod "$MODDIR"/gzvm.ko
insmod "$MODDIR"/vcan.ko
insmod "$MODDIR"/virtio_pci_modern_dev.ko
insmod "$MODDIR"/pppox.ko
insmod "$MODDIR"/nhc_fragment.ko
insmod "$MODDIR"/l2tp_ppp.ko
insmod "$MODDIR"/cctrng.ko
insmod "$MODDIR"/btsdio.ko
insmod "$MODDIR"/regmap-ram.ko
insmod "$MODDIR"/rtl8150.ko
insmod "$MODDIR"/nhc_ipv6.ko
insmod "$MODDIR"/hci_uart.ko
insmod "$MODDIR"/ptp.ko
insmod "$MODDIR"/bsd_comp.ko
insmod "$MODDIR"/can-dev.ko
insmod "$MODDIR"/hidp.ko
insmod "$MODDIR"/regmap-kunit.ko
insmod "$MODDIR"/cdc_ncm.ko
insmod "$MODDIR"/ftdi_sio.ko
insmod "$MODDIR"/kunit-example-test.ko
insmod "$MODDIR"/r8153_ecm.ko
insmod "$MODDIR"/soc-topology-test.ko


